//! Embeds the shipped rule set (PROTOCOL.md §9, "the shipped source").
//!
//! `default_rules/<group>/*.json` is read at build time and the *list* is emitted as Rust
//! source; each entry's contents are pulled in by `include_str!`, so the set travels inside
//! the binary and `jev rules init` can write it back out without a data directory to install.
//!
//! **The build must not fail when the directory is empty or absent.** The shipped set is
//! authored as ordinary rule files, one per file, by people editing the tree — a build that
//! refused to compile until the last one landed would make every rule a build-breaking
//! dependency of every other, and a build that hard-coded a file list would need editing for
//! every rule, which is the same coupling with more steps. So the list is globbed here: an
//! empty directory emits an empty slice, and a repository with zero shipped rules behaves
//! exactly as it did before this file existed.
//!
//! `std::fs` and one level of recursion: no new dependency. The order is the sorted relative
//! path, so the emitted list — and with it the rules' hash (PROTOCOL §5) — is a function of the
//! tree and not of the filesystem's enumeration order.

use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let root = manifest.join("default_rules");

    let mut files = Vec::new();
    collect(&root, &mut files);
    // Sorted by relative path: the set's hash must not depend on readdir's order.
    files.sort();

    // With the directory present, cargo watches it recursively, so a rule file landing (or
    // being edited or deleted) rebuilds with the new set. With it absent there is nothing to
    // watch and no `rerun-if-changed` is printed at all, which leaves cargo's default in force:
    // any change under the package directory reruns this script, so the first rule file to
    // appear is picked up.
    if root.is_dir() {
        println!("cargo:rerun-if-changed={}", root.display());
    }

    let mut out = String::from(
        "// Generated by build.rs from `default_rules/<group>/*.json`. Do not edit; edit the\n\
         // rule files, and this list follows them.\n\
         &[\n",
    );
    for path in &files {
        let name = path
            .strip_prefix(&root)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        out.push_str(&format!(
            "    ({name:?}, include_str!({:?})),\n",
            path.display().to_string()
        ));
    }
    out.push_str("]\n");

    let dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(dir.join("default_rules.rs"), out).expect("write default_rules.rs");
}

/// Every `*.json` under `dir`, at any depth, in no particular order (`files` is sorted after).
///
/// A missing directory is zero files, never an error: the authoring sessions write into this
/// tree while the code that ships it is being built.
fn collect(dir: &Path, files: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, files);
        } else if path.extension().is_some_and(|e| e == "json") {
            files.push(path);
        }
    }
}
